import string

DELIMITERS = ["/", ":", "·", ".", "•", "×", "*"]

# Amino acid base names and their primary substitution sites
AMINO_ACID_SUB_SITES = {
    "lys": ("lysine", "Nε"),
    "arg": ("arginine", "Nω"),
    "his": ("histidine", "N³"),
    "ser": ("serine", "O"),
    "thr": ("threonine", "O"),
    "tyr": ("tyrosine", "O"),
    "cys": ("cysteine", "S"),
    "asp": ("aspartic acid", "β"),
    "glu": ("glutamic acid", "γ"),
    "asn": ("asparagine", "Nδ"),
    "gln": ("glutamine", "Nε"),
    "trp": ("tryptophan", "N¹"),
    "met": ("methionine", "S"),
    "orn": ("ornithine", "Nδ"),
    "hse": ("homoserine", "O"),
}

# Protecting group definitions
PROTECTING_GROUPS = {
    "boc": "(tert-butoxycarbonyl)",
    "z": "(benzyloxycarbonyl)",
    "cbz": "(benzyloxycarbonyl)",
    "fmoc": "(9-fluorenylmethoxycarbonyl)",
    "ac": "(acetyl)",
    "alloc": "(allyloxycarbonyl)",
    "dde": "((1-(4,4-dimethyl-2,6-dioxocyclohexylidene)ethyl))",
    "ivdde": "((1-(4,4-dimethyl-2,6-dioxocyclohexylidene)-3-methylbutyl))",
    "mtt": "(4-methyltrityl)",
    "proc": "(propargyloxycarbonyl)",
    "pbf": "(2,2,4,6,7-pentamethyldihydrobenzofuran-5-sulfonyl)",
    "tos": "(tosyl)",
    "mtr": "(4-methoxy-2,3,6-trimethylbenzenesulfonyl)",
    "pmc": "(2,2,5,7,8-pentamethylchroman-6-sulfonyl)",
    "no2": "(nitro)",
    "trt": "trityl",
    "bn": "benzyl",
    "bzl": "benzyl",
    "dnp": "2,4-dinitrophenyl",
    "tbu": "tert-butyl",
    "acm": "acetamidomethyl",
    "stbu": "tert-butyl",
    "mob": "4-methoxybenzyl",
    "mmt": "4-methoxytrityl",
    "npys": "3-nitro-2-pyridinesulfenyl",
    "xan": "(xanthenyl)",
    "for": "formyl",
    "hoc": "1-(1-adamantyl)-1-methylethoxycarbonyl",
    "o": "oxide",
    "o2": ",S-dioxide",
    "otbu": "tert-butyl ester",
    "obut": "tert-butyl ester",  # typo variant?
    "obn": "benzyl ester",
    "ome": "methyl ester",
    "oet": "ethyl ester",
    "oall": "allyl ester",
    "ofm": "9-fluorenylmethyl ester",
}

# Special cases that don't follow the standard pattern
SPECIAL_CASES = {
    "tyr(2-br-z)": ("tyrosine", "O-2-bromobenzyloxycarbonyl"),
    "tyr(2,6-cl2-bn)": ("tyrosine", "O-2,6-dichlorobenzyl"),
    "met(o2)": ("methionine", "S,S-dioxide"),
}

AA_FULL = {
    "gly": ["glycine", "glycyl"],
    "ala": ["alanine", "alanyl"],
    "val": ["valine", "valyl"],
    "leu": ["leucine", "leucyl"],
    "leuc": ["leucine", "leucyl"],
    "ile": ["isoleucine", "isoleucyl"],
    "ileu": ["isoleucine", "isoleucyl"],
    "ser": ["serine", "seryl"],
    "thr": ["threonine", "threonyl"],
    "cys": ["cysteine", "cysteinyl"],
    "met": ["methionine", "methionyl"],
    "phe": ["phenylalanine", "phenylalanyl"],
    "tyr": ["tyrosine", "tyrosyl"],
    "trp": ["tryptophan", "tryptophyl"],
    "asp": ["aspartic acid", "aspartyl"],
    "glu": ["glutamic acid", "glutamyl"],
    "asn": ["asparagine", "asparaginyl"],
    "gln": ["glutamine", "glutaminyl"],
    "lys": ["lysine", "lysyl"],
    "arg": ["arginine", "arginyl"],
    "his": ["histidine", "histidyl"],
    "pro": ["proline", "prolyl"],
    "hyp": ["4-hydroxyproline", "4-hydroxyprolyl"],
    "orn": ["ornithine", "ornithyl"],
    "dab": ["2,4-diaminobutyric acid", "2,4-diaminobutyryl"],
    "dap": ["2,3-diaminopropionic acid", "2,3-diaminopropionyl"],
    "sar": ["sarcosine", "sarcosyl"],
    "abu": ["2-aminobutyric acid", "2-aminobutyryl"],
    "aib": ["2-aminoisobutyric acid", "2-aminoisobutyryl"],
    "nva": ["norvaline", "norvalyl"],
    "nle": ["norleucine", "norleucyl"],
    "hse": ["homoserine", "homoserinyl"],
    "hcy": ["homocysteine", "homocysteinyl"],
    "pen": ["penicillamine", "penicillaminyl"],
    "sec": ["selenocysteine", "selenocysteinyl"],
    "pyl": ["pyrrolysine", "pyrrolysinyl"],
    "aad": ["2-aminoadipic acid", "2-aminoadipyl"],
    "aan": ["α-asparagine", "α-asparaginyl"],
    "aca": ["2-aminocapric acid", "2-aminocapryl"],
    "agn": ["α-glutamine", "α-glutaminyl"],
    "ahx": ["6-aminohexanoic acid", "6-aminohexanoyl"],
    "apm": ["2-aminopimelic acid", "2-aminopimelyl"],
    "app": [
        "γ-amino-β-hydroxybenzenepentanoic acid",
        "γ-amino-β-hydroxybenzenepentanoyl",
    ],
    "asu": ["2-aminosuberic acid", "2-aminosuberyl"],
    "azagly": ["2-azaglycine", "2-azaglycyl"],
    "aze": ["2-carboxyazetidine", "2-carboxyazetidinyl"],
    "bal": ["β-alanine", "β-alanyl"],
    "bas": ["β-aspartic acid", "β-aspartyl"],
    "bly": ["3,6-diaminohexanoic acid", "3,6-diaminohexanoyl"],
    "bua": ["butanoic acid", "butanoyl"],
    "bux": ["4-amino-3-hydroxybutanoic acid", "4-amino-3-hydroxybutanoyl"],
    "cap": [
        "γ-amino-β-hydroxycyclohexanepentanoic acid",
        "γ-amino-β-hydroxycyclohexanepentanoyl",
    ],
    "cha": ["3-cyclohexylalanine", "3-cyclohexylalanyl"],
    "cit": ["N5-aminocarbonylornithine", "N5-aminocarbonylornithyl"],
    "cya": ["3-sulfoalanine", "3-sulfoalanyl"],
    "dpm": ["diaminopimelic acid", "diaminopimelyl"],
    "dpr": ["2,3-diaminopropanoic acid", "2,3-diaminopropanoyl"],
    "dsu": ["2,7-diaminosuberic acid", "2,7-diaminosuberyl"],
    "edc": ["S-ethylthiocysteine", "S-ethylthiocysteinyl"],
    "ggu": ["γ-glutamic acid", "γ-glutamyl"],
    "gla": ["γ-carboxyglutamic acid", "γ-carboxyglutamyl"],
    "glc": ["hydroxyacetic acid", "hydroxyacetyl"],
    "glp": ["pyroglutamic acid", "pyroglutamyl"],
    "pglu": ["pyroglutamic acid", "pyroglutamyl"],
    "har": ["homoarginine", "homoarginyl"],
    "hhs": ["homohistidine", "homohistidinyl"],
    "hiv": ["2-hydroxyisovaleric acid", "2-hydroxyisovaleryl"],
    "hva": ["2-hydroxypentanoic acid", "2-hydroxypentanoyl"],
    "hyl": ["5-hydroxylysine", "5-hydroxylysinyl"],
    "igl": ["α-amino-2-indanacetic acid", "α-amino-2-indanacetyl"],
    "iva": ["isovaline", "isovalinyl"],
    "lac": ["2-hydroxypropanoic acid", "2-hydroxypropanoyl"],
    "maa": ["mercaptoacetic acid", "mercaptoacetyl"],
    "mba": ["mercaptobutanoic acid", "mercaptobutanoyl"],
    "mhp": ["3-hydroxy-4-methylproline", "3-hydroxy-4-methylprolyl"],
    "mpa": ["mercaptopropanoic acid", "mercaptopropanoyl"],
    "nal": ["3-naphthylalanine", "3-naphthylalanyl"],
    "nphe": ["N-benzylglycine", "N-benzylglycyl"],
    "nty": ["nortyrosine", "nortyrosinyl"],
    "oaa": ["ω-amino acid", "ω-aminoacyl"],
    "oic": ["2-carboxyoctahydroindole", "2-carboxyoctahydroindolyl"],
    "3-pal": ["3-(3-pyridyl)-alanine", "3-(3-pyridyl)-alanyl"],
    "phg": ["2-phenylglycine", "2-phenylglycyl"],
    "pip": ["2-carboxypiperidine", "2-carboxypiperidyl"],
    "pmp": [
        "β,β-cyclopentamethylene-β-mercaptopropionic acid",
        "β,β-cyclopentamethylene-β-mercaptopropionyl",
    ],
    "pser": ["phospho-L-serine", "phospho-L-serinyl"],
    "pthr": ["phospho-L-threonine", "phospho-L-threoninyl"],
    "ptyr": ["phospho-L-tyrosine", "phospho-L-tyrosinyl"],
    "pya(4)": ["3-(4-pyridinyl)-alanine", "3-(4-pyridinyl)-alanyl"],
    "spg": ["1-amino-1-carboxycyclopentane", "1-amino-1-carboxycyclopentyl"],
    "sta": ["statine", "statinyl"],
    "thi": ["3-thienylalanine", "3-thienylalanyl"],
    "tac": ["2-tolylaminophenylcabonyl", "2-tolylaminophenylcabonyl"],
    "tic": ["3-carboxyisoquinoline", "3-carboxyisoquinolinyl"],
    "tle": ["3-methylvaline", "3-methylvalyl"],
    "tml": ["ε-N-trimethyllysine", "ε-N-trimethyllysinyl"],
    "tza": ["3-thiazolylalanine", "3-thiazolylalanyl"],
    "wil": [
        "α-amino-2,4-dioxopyrimidinepropanoic acid",
        "α-amino-2,4-dioxopyrimidinepropanoyl",
    ],
}

N_CAPS = {
    "h2n": "",
    "h": "",
    "nh2": "",
    "cbz": "benzyloxycarbonyl",
    "z": "benzyloxycarbonyl",
    "boc": "tert-butoxycarbonyl",
    "tboc": "tert-butoxycarbonyl",
    "fmoc": "9-fluorenylmethoxycarbonyl",
    "alloc": "allyloxycarbonyl",
    "troc": "2,2,2-trichloroethoxycarbonyl",
    "teoc": "2-(trimethylsilyl)ethoxycarbonyl",
    "poc": "propargyloxycarbonyl",
    "moc": "methoxycarbonyl",
    "eoc": "ethoxycarbonyl",
    "azoc": "2-azidobenzyloxycarbonyl",
    "nvoc": "6-nitroveratryloxycarbonyl",
    "ddz": "3,5-dimethoxybenzyloxycarbonyl",
    "ac": "acetyl",
    "piv": "pivaloyl",
    "bz": "benzoyl",
    "tos": "tosyl",
    "ts": "tosyl",
    "ms": "mesyl",
    "mes": "mesyl",
    "tf": "trifluoromethanesulfonyl",
    "ns": "4-nitrobenzenesulfonyl",
    "dts": "dithiasuccinoyl",
    "for": "formyl",
    "tfa": "trifluoroacetyl",
    "mtr": "4-methoxy-2,3,6-trimethylbenzenesulfonyl",
    "pmc": "2,2,5,7,8-pentamethylchroman-6-sulfonyl",
    "pbf": "2,2,4,6,7-pentamethyldihydrobenzofuran-5-sulfonyl",
    "bn": "benzyl",
    "pmb": "4-methoxybenzyl",
    "dmb": "2,4-dimethoxybenzyl",
    "tmb": "2,4,6-trimethoxybenzyl",
    "trt": "trityl",
    "mmt": "4-methoxytrityl",
    "dmt": "4,4'-dimethoxytrityl",
    "myr": "Myristoyl",
}

C_CAPS = {
    "h": "",  # typo?
    "oh": "",
    "ome": "methyl ester",
    "och3": "methyl ester",
    "oet": "ethyl ester",
    "otbu": "tert-butyl ester",
    "obn": "benzyl ester",
    "obzl": "benzyl ester",
    "oallyl": "allyl ester",
    "oall": "allyl ester",
    "oph": "phenyl ester",
    "otmse": "2-(trimethylsilyl)ethyl ester",
    "otbdms": "tert-butyldimethylsilyl ester",
    "otips": "triisopropylsilyl ester",
    "ofm": "9-fluorenylmethyl ester",
    "odmb": "2,4-dimethoxybenzyl ester",
    "opmb": "4-methoxybenzyl ester",
    "onp": "4-nitrophenyl ester",
    "opfp": "pentafluorophenyl ester",
    "osu": "N-hydroxysuccinimidyl ester",
    "obt": "benzotriazol-1-yl ester",
    "oat": "7-azabenzotriazol-1-yl ester",
    "nh2": "amide",
    "nh": "amine",  # typo?
    "nhme": "N-methylamide",
    "nme2": "N,N-dimethylamide",
    "nhet": "N-ethylamide",
    "net2": "N,N-diethylamide",
    "nhbn": "N-benzylamide",
    "nhph": "N-phenylamide",
    "nhnh2": "hydrazide",
    "nhnh": "hydrazide",  # typo?
    "conhnh2": "hydrazide",
    "cho": "aldehyde",
    "ch2oh": "alcohol",
    "conh2": "amide",
    "cf3": "trifluoromethane",
}

COUNTER_ACIDS = {
    "hcl": "hydrochloride",
    "2hcl": "dihydrochloride",
    "3hcl": "trihydrochloride",
    "4hcl": "tetrahydrochloride",
    "hydrochloride": "hydrochloride",
    "hbr": "hydrobromide",
    "2hbr": "dihydrobromide",
    "hci": "hydroiodide",
    "tfa": "trifluoroacetate",
    "trifluoroacetate": "trifluoroacetate",
    "acetate": "acetate",
    "diacetate": "diacetate",
    "acoh": "acetate",
    "2acoh": "diacetate",
}

PREFIX_MAP = {
    "me": "methyl-",
    "(me)": "methyl-",
    "et": "ethyl-",
    "(et)": "ethyl-",
    "ac": "acetyl-",
    "(ac)": "acetyl-",
    "for": "formyl-",
    "(for)": "formyl-",
    "bz": "benzoyl-",
    "(bz)": "benzoyl-",
    "cbz": "carbobenzyloxy-",
    "(cbz)": "carbobenzyloxy-",
    "z": "carbobenzyloxy-",
    "(z)": "carbobenzyloxy-",
    "boc": "tert-butoxycarbonyl-",
    "(boc)": "tert-butoxycarbonyl-",
    "fmoc": "fluorenylmethoxycarbonyl-",
    "(fmoc)": "fluorenylmethoxycarbonyl-",
    "ts": "tosyl-",
    "(ts)": "tosyl-",
    "ms": "mesyl-",
    "(ms)": "mesyl-",
    "tf": "trifluoroacetyl-",
    "(tf)": "trifluoroacetyl-",
}

GREEK_LETTERS = [
    "α",
    "β",
    "γ",
    "δ",
    "ε",
    "ζ",
    "η",
    "θ",
    "ι",
    "κ",
    "λ",
    "μ",
    "ν",
    "ξ",
    "ο",
    "π",
    "ρ",
    "σ",
    "τ",
    "υ",
    "φ",
    "χ",
    "ψ",
    "ω",
]

NON_LATIN1_REPLACEMENTS = {
    # Superscripts
    "⁰": "0",
    "¹": "1",
    "²": "2",
    "³": "3",
    "⁴": "4",
    "⁵": "5",
    "⁶": "6",
    "⁷": "7",
    "⁸": "8",
    "⁹": "9",
    "⁺": "+",
    "⁻": "-",
    "⁽": "(",
    "⁾": ")",
    # Subscripts
    "₀": "0",
    "₁": "1",
    "₂": "2",
    "₃": "3",
    "₄": "4",
    "₅": "5",
    "₆": "6",
    "₇": "7",
    "₈": "8",
    "₉": "9",
    "₊": "+",
    "₋": "-",
    "₍": "(",
    "₎": ")",
    # Greek letters
    "α": "alpha",
    "β": "beta",
    "ß": "beta",
    "γ": "gamma",
    "δ": "delta",
    "ε": "epsilon",
    "ζ": "zeta",
    "η": "eta",
    "θ": "theta",
    "ι": "iota",
    "κ": "kappa",
    "λ": "lambda",
    "μ": "mu",
    "µ": "mu",  # Do not remove - this mu is different from the previous!?
    "ν": "nu",
    "ξ": "xi",
    "ο": "omicron",
    "π": "pi",
    "ρ": "rho",
    "σ": "sigma",
    "τ": "tau",
    "υ": "upsilon",
    "φ": "phi",
    "χ": "chi",
    "ψ": "psi",
    "ω": "omega",
    "Α": "Alpha",
    "Β": "Beta",
    "Γ": "Gamma",
    "Δ": "Delta",
    "Ε": "Epsilon",
    "Ζ": "Zeta",
    "Η": "Eta",
    "Θ": "Theta",
    "Ι": "Iota",
    "Κ": "Kappa",
    "Λ": "Lambda",
    "Μ": "Mu",
    "Ν": "Nu",
    "Ξ": "Xi",
    "Ο": "Omicron",
    "Π": "Pi",
    "Ρ": "Rho",
    "Σ": "Sigma",
    "Τ": "Tau",
    "Υ": "Upsilon",
    "Φ": "Phi",
    "Χ": "Chi",
    "Ψ": "Psi",
    "Ω": "Omega",
    # Other symbols
    "×": "x",
    "·": ".",
    "−": "-",
    "–": "-",
    "—": "-",
    "‐": "-",
    "‑": "-",
    "⁃": "-",
    "﹣": "-",
    "－": "-",
    "°": "",
    "Å": "A",
    "’": "'",
    "′": "'",
    "´": "'",
    "″": '"',
    "“": '"',
    "”": '"',
    "®": "",
    "™": "",
    "•": ".",
    "±": "+-",
    "→": "",
    "ü": "u",
    "ø": "o",
    "ö": "o",
    "?": "",
    "%": "",
    "≤": "<=",
    "≥": ">=",
    # Non standard spaces
    "\u00a0": " ",
    "\u2002": " ",
    "\u2003": " ",
    "\u2009": " ",
    "\u200a": " ",
    "\u200b": "",
    # Encoding errors from utf-8 to windows-1252
    "â\x81°": "0",
    "Â¹": "1",
    "Â²": "2",
    "Â³": "3",
    "â\x81´": "4",
    "â\x81µ": "5",
    "â\x81¶": "6",
    "â\x81·": "7",
    "â\x81¸": "8",
    "â\x81¹": "9",
    "â\x81º": "+",
    "â\x81»": "-",
    "â\x81½": "(",
    "â\x81¾": ")",
    "â‚€": "0",
    "â‚\x81": "1",
    "â‚‚": "2",
    "â‚ƒ": "3",
    "â‚„": "4",
    "â‚…": "5",
    "â‚†": "6",
    "â‚‡": "7",
    "â‚ˆ": "8",
    "â‚‰": "9",
    "â‚Š": "+",
    "â‚‹": "-",
    "â‚\x8d": "(",
    "â‚Ž": ")",
    "Î±": "alpha",
    "Î²": "beta",
    "ÃŸ": "beta",
    "Î³": "gamma",
    "Î´": "delta",
    "Îµ": "epsilon",
    "Î¶": "zeta",
    "Î·": "eta",
    "Î¸": "theta",
    "Î¹": "iota",
    "Îº": "kappa",
    "Î»": "lambda",
    "Î¼": "mu",
    "Âµ": "mu",
    "Î½": "nu",
    "Î¾": "xi",
    "Î¿": "omicron",
    "Ï€": "pi",
    "Ï\x81": "rho",
    "Ïƒ": "sigma",
    "Ï„": "tau",
    "Ï…": "upsilon",
    "Ï†": "phi",
    "Ï‡": "chi",
    "Ïˆ": "psi",
    "Ï‰": "omega",
    "Î‘": "Alpha",
    "Î’": "Beta",
    "Î“": "Gamma",
    "Î”": "Delta",
    "Î•": "Epsilon",
    "Î–": "Zeta",
    "Î—": "Eta",
    "Î˜": "Theta",
    "Î™": "Iota",
    "Îš": "Kappa",
    "Î›": "Lambda",
    "Îœ": "Mu",
    "Î\x9d": "Nu",
    "Îž": "Xi",
    "ÎŸ": "Omicron",
    "Î\xa0": "Pi",
    "Î¡": "Rho",
    "Î£": "Sigma",
    "Î¤": "Tau",
    "Î¥": "Upsilon",
    "Î¦": "Phi",
    "Î§": "Chi",
    "Î¨": "Psi",
    "Î©": "Omega",
    "Ã—": "x",
    "Â·": ".",
    "âˆ’": "-",
    "â€“": "-",
    "â€”": "-",
    "â€\x90": "-",
    "â€‘": "-",
    "â\x81ƒ": "-",
    "ï¹£": "-",
    "ï¼\x8d": "-",
    "Â°": "",
    "Ã…": "A",
    "â€™": "'",
    "â€²": "'",
    "Â´": "'",
    "â€³": '"',
    "â€œ": '"',
    "â€\x9d": '"',
    "Â®": "",
    "â„¢": "",
    "â€¢": ".",
    "Â±": "+-",
    "â†’": "",
    "Ã¼": "u",
    "Ã¸": "o",
    "Ã¶": "o",
    "?": "",
    "%": "",
    "â‰¤": "<=",
    "â‰¥": ">=",
    "Â\xa0": " ",
    "â€‚": " ",
    "â€ƒ": " ",
    "â€‰": " ",
    "â€Š": " ",
    "â€‹": "",
    # Encoding errors from utf-8 to html entities
    "&#8304;": "0",
    "&#185;": "1",
    "&#178;": "2",
    "&#179;": "3",
    "&#8308;": "4",
    "&#8309;": "5",
    "&#8310;": "6",
    "&#8311;": "7",
    "&#8312;": "8",
    "&#8313;": "9",
    "&#8314;": "+",
    "&#8315;": "-",
    "&#8317;": "(",
    "&#8318;": ")",
    "&#8320;": "0",
    "&#8321;": "1",
    "&#8322;": "2",
    "&#8323;": "3",
    "&#8324;": "4",
    "&#8325;": "5",
    "&#8326;": "6",
    "&#8327;": "7",
    "&#8328;": "8",
    "&#8329;": "9",
    "&#8330;": "+",
    "&#8331;": "-",
    "&#8333;": "(",
    "&#8334;": ")",
    "&#945;": "alpha",
    "&#946;": "beta",
    "&#947;": "gamma",
    "&#948;": "delta",
    "&#949;": "epsilon",
    "&#950;": "zeta",
    "&#951;": "eta",
    "&#952;": "theta",
    "&#953;": "iota",
    "&#954;": "kappa",
    "&#955;": "lambda",
    "&#956;": "mu",
    "&#957;": "nu",
    "&#958;": "xi",
    "&#959;": "omicron",
    "&#960;": "pi",
    "&#961;": "rho",
    "&#963;": "sigma",
    "&#964;": "tau",
    "&#965;": "upsilon",
    "&#966;": "phi",
    "&#967;": "chi",
    "&#968;": "psi",
    "&#969;": "omega",
    "&#913;": "Alpha",
    "&#914;": "Beta",
    "&#915;": "Gamma",
    "&#916;": "Delta",
    "&#917;": "Epsilon",
    "&#918;": "Zeta",
    "&#919;": "Eta",
    "&#920;": "Theta",
    "&#921;": "Iota",
    "&#922;": "Kappa",
    "&#923;": "Lambda",
    "&#924;": "Mu",
    "&#925;": "Nu",
    "&#926;": "Xi",
    "&#927;": "Omicron",
    "&#928;": "Pi",
    "&#929;": "Rho",
    "&#931;": "Sigma",
    "&#932;": "Tau",
    "&#933;": "Upsilon",
    "&#934;": "Phi",
    "&#935;": "Chi",
    "&#936;": "Psi",
    "&#937;": "Omega",
    "&#215;": "x",
    "&#183;": ".",
    "&#8722;": "-",
    "&#8211;": "-",
    "&#8212;": "-",
    "&#8208;": "-",
    "&#8209;": "-",
    "&#8259;": "-",
    "&#65123;": "-",
    "&#65293;": "-",
    "&#176;": "",
    "&#197;": "A",
    "&#8217;": "'",
    "&#8242;": "'",
    "&#8243;": '"',
    "&#174;": "",
    "&#8482;": "",
    "&#8226;": ".",
    "&#177;": "+-",
    "&#8594;": "",
    "&#252;": "u",
    "&#248;": "o",
    "&#246;": "o",
    "&#160;": " ",
    "&#8194;": " ",
    "&#8195;": " ",
    "&#8201;": " ",
    "&#8202;": " ",
    "&#8203;": "",
}

COMMON_CHARS_WHITELIST = list(
    string.ascii_letters + string.digits + string.punctuation + " "
)

ALLOWED_CHARS_WHITELIST = list(
    set(
        string.ascii_letters
        + string.digits
        + string.punctuation
        + " "
        + "".join(list(NON_LATIN1_REPLACEMENTS.values()))
    )
)

OCR_SUBSTITUTIONS = {
    # Digit confusions
    "0": ["O", "o", "Q", "D", "C", "@", "()"],
    "1": ["l", "I", "i", "|", "]", "[", "!", "t", "f", "L"],
    "2": ["Z", "z", "?", "7"],
    "3": ["E", "e", "B", "8", "}", "?", "S"],
    "4": ["A", "a", "H", "h", "y", "+"],
    "5": ["S", "s"],
    "6": ["G", "b", "&", "E"],
    "7": ["T", "Y", "]", "/", "1", ")", ">", "?"],
    "8": ["B", "&", "$", "S", "3", "E"],
    "9": ["g", "q"],
    # Letter confusions
    "O": ["0"],
    "o": ["0"],
    "l": ["1", "I"],
    "I": ["1", "l", "|", "]", "["],
    "i": ["1"],
    "Z": ["2"],
    "z": ["2"],
    "S": ["5", "$"],
    "s": ["5", "$"],
    "G": ["6"],
    "B": ["8"],
    "g": ["9", "cj"],
    "q": ["9"],
    # Common OCR letter confusions
    "rn": ["m"],
    "ri": ["n"],
    "m": ["rn", "ni", "in"],
    "ni": ["m"],
    "in": ["m"],
    "vv": ["w"],
    "w": ["vv"],
    "cl": ["d"],
    "d": ["cl"],
    "li": ["h"],
    "h": ["li"],
    "nn": ["m"],
    "ii": ["n"],
    "rt": ["n"],
    "cj": ["g"],
    "n": ["ii", "ri", "rt"],
    "lo": ["b"],
    "b": ["lo"],
    # Separators and Primes
    ",": [".", "'", "`"],
    ".": [",", "-"],
    "-": ["_", "~", "."],
    "_": ["-"],
    "'": [",", "`", "1"],
    # Brackets vs Lines
    "(": ["C", "{", "["],
    ")": ["J", "}", "]", "l"],
    "[": ["L", "(", "I", "l"],
    "]": ["I", "1", ")"],
    "|": ["l", "I", "1", "/"],
    "/": ["l", "I", "1", "|"],
}

KEYBOARD_NEIGHBOR_SUBSTITUTIONS = {
    "a": ["q", "w", "s", "z"],
    "b": ["v", "g", "h", "n"],
    "c": ["x", "d", "f", "v"],
    "d": ["s", "e", "r", "f", "c", "x"],
    "e": ["w", "s", "d", "r"],
    "f": ["d", "r", "t", "g", "v", "c"],
    "g": ["f", "t", "y", "h", "b", "v"],
    "h": ["g", "y", "u", "j", "n", "b"],
    "i": ["u", "j", "k", "o"],
    "j": ["h", "u", "i", "k", "n", "m"],
    "k": ["j", "i", "o", "l", "m"],
    "l": ["k", "o", "p"],
    "m": ["n", "j", "k"],
    "n": ["b", "h", "j", "m"],
    "o": ["i", "k", "l", "p"],
    "p": ["o", "l"],
    "q": ["w", "a"],
    "r": ["e", "d", "f", "t"],
    "s": ["a", "w", "e", "d", "x", "z"],
    "t": ["r", "f", "g", "y"],
    "u": ["y", "h", "j", "i"],
    "v": ["c", "f", "g", "b"],
    "w": ["q", "a", "s", "e"],
    "x": ["z", "s", "d", "c"],
    "y": ["t", "g", "h", "u"],
    "z": ["a", "s", "x"],
}
